# swagger.yml

openapi: 3.0.3
info:
  title: Flask REST API
  description: Una API para manejar redes
  version: "0.1.0"
  
servers:
  - url: http://localhost:8000
  description: REST API para governar redes en GNS3

paths:
  /topologia:
    get:
      operationId: topology_scan.scan_all
      tags:
        - topology
      summary: Regresar json con los routers existentes en la topología y ligas a sus routers vecinos
      responses:
        "201":
          description: Se escaneo toda la topologia
        "404":
          description: No se encontro ninguna conexion


components:
  schemas:
    Host:
      type: object
      required:
        - hname
      properties:
        hname:
          type: string
        ip:
          type: string
