# swagger.yml

openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "Una API para manejar redes"
  version: "1.0.0"

servers:
  - url: "/"
  description: REST API para governar redes en GNS3

components:
  schemas:
    Host:
      type: "object"
      required:
        - hname
      properties:
        hname:
          type: "string"
        ip:
          type: "string"

paths:
  /usuarios:
    get:
      operationId: "topology_scan.scan_all"
      tags:
        - "Usuarios"
      summary: "Regresar json con todos los usuarios existentes en los routers, incluyendo nombre, permisos y dispositivos donde existe (URL a routers donde exista cada usuario)."
      responses:
        "200":
          description: "Se encontro ususarios"
    
    post:
      operationId: "topology_scan.scan_all"
      tags:
        - "Usuarios"
      summary: "Regresar json con todos los usuarios existentes en los routers, incluyendo nombre, permisos y dispositivos donde existe (URL a routers donde exista cada usuario)."
      responses:
        "200":
          description: "Se encontro ususarios"
    
    put:
      operationId: "topology_scan.scan_all"
      tags:
        - "Usuarios"
      summary: "Regresar json con todos los usuarios existentes en los routers, incluyendo nombre, permisos y dispositivos donde existe (URL a routers donde exista cada usuario)."
      responses:
        "200":
          description: "Se encontro ususarios"
    
    delete:
      operationId: "topology_scan.scan_all"
      tags:
        - "Usuarios"
      summary: "Regresar json con todos los usuarios existentes en los routers, incluyendo nombre, permisos y dispositivos donde existe (URL a routers donde exista cada usuario)."
      responses:
        "200":
          description: "Se encontro ususarios"
  
  /routes:
    get:
      operationId: "topology_scan.scan_all"
      tags:
        - "Routers"
      summary: "Regresa la información general de todos los routers de la topología. Incluyendo Nombre, IP loopback, IP administrativa, rol, empresa, Sistema operativo y ligas a las interfaces activas."
      responses:
        "200":
          description: "Se encontraron Routers"
  

  /topologia:
    
    get:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Regresar json con los routers existentes en la topología y ligas a sus routers vecinos"
      responses:
        "200":
          description: "Se escaneo toda la topologia"
 
    post:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Activa un demonio que cada 5 minutos explora la red para detectar cambios en la misma"
      responses:
        "200":
          description: "Se activo un daemon para explorar la red"
 
    put:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Permite cambiar el intervalo de tiempo en el que el demonio explora la topología"
      responses:
        "200":
          description: "Se cambio el intervalo de tiempo"
 
    delete:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Detiene el demonio que explora la topologia"
      responses:
        "200":
          description: "Se detuvo el daemon"