# swagger.yml

openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "Una API para manejar redes"
  version: "0.1.0"

servers:
  - url: "/"

components:
  schemas:
    Host:
      type: "object"
      required:
        - hname
      properties:
        hname:
          type: "string"
        ip:
          type: "string"

paths:
  /topologia:
    
    get:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Regresar json con los routers existentes en la topología y ligas a sus routers vecinos"
      responses:
        "200":
          description: "Se escaneo toda la topologia"
 
    post:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Activa un demonio que cada 5 minutos explora la red para detectar cambios en la misma"
      responses:
        "200":
          description: "Se activo un daemon para explorar la red"
 
    put:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Permite cambiar el intervalo de tiempo en el que el demonio explora la topología"
      responses:
        "200":
          description: "Se cambio el intervalo de tiempo"
 
    delete:
      operationId: "topology_scan.scan_all"
      tags:
        - "topology"
      summary: "Detiene el demonio que explora la topologia"
      responses:
        "200":
          description: "Se detuvo el daemon"